[package]
name = "schema_chage_shards_reproducer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
scylla-cql = "0.0.9"
uuid = "1.0"
futures = "0.3"